name: CoderDojoDC
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables"]
plugins:
  - jekyll-redirect-from
github: https://github.com/CoderDojoDC
about: A Washington, D.C. area free and open programming club for kids, 7-17.
google_analytics_id: UA-16709386-3
urls:
  - text: join us
    url: https://meetup.com/Rockville-RSC-Makerspace/
  - text: faq
    url: /faq
  - text: mentor
    url: /mentor
  - text: donate
    url: /donate
  - text: showcase
    url: /showcase
  - text: archive
    url: /archive
